# Generated by Django 3.1.3 on 2020-11-25 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.IntegerField(unique=True)),
                ('community_name', models.CharField(max_length=100, unique=True)),
                ('community_abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('excise_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('sales_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('region', models.CharField(choices=[('CO', 'Central Oregon'), ('PDX', 'PDX & Vancouver'), ('TRI', 'Tri Cities')], default='CO', max_length=10)),
            ],
            options={
                'ordering': ('community_name',),
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('plan',),
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_id', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('base_price', models.IntegerField(default=0)),
                ('lot_cost', models.IntegerField(default=0)),
                ('permit_cost', models.IntegerField(default=0)),
                ('hard_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('base_price', models.IntegerField(default=0)),
                ('lot_cost', models.IntegerField(default=0)),
                ('permit_cost', models.IntegerField(default=0)),
                ('hard_cost', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.community')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plans')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('lot_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.community')),
            ],
        ),
    ]
