# Generated by Django 3.1.3 on 2020-12-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201130_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('community_id',)},
        ),
        migrations.AlterField(
            model_name='community',
            name='excise_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='community',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plat',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
