# Generated by Django 3.1.3 on 2020-12-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201130_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='region',
            field=models.CharField(choices=[('CO', 'CO'), ('PDX', 'PDX'), ('TRI', 'TRI')], default='CO', max_length=10),
        ),
    ]
