# Generated by Django 3.1.3 on 2020-12-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_phase_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plat',
            options={'ordering': ('description',)},
        ),
    ]
