# Generated by Django 3.1.3 on 2020-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201201_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformalist',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
