# Generated by Django 3.1.3 on 2020-12-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201203_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartsheet_id', models.CharField(max_length=100, unique=True)),
                ('schedule_type', models.CharField(choices=[('Plat', 'Plat'), ('Other', 'Other')], default='Plat', max_length=10)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.community')),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.plat')),
            ],
        ),
    ]
