# Generated by Django 3.1.3 on 2020-12-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
