# Generated by Django 3.1.3 on 2020-12-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformalist',
            name='tied_out',
            field=models.BooleanField(default=False),
        ),
    ]
