# Generated by Django 3.1.3 on 2020-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_proformalist_tied_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proforma',
            old_name='lot_cost',
            new_name='lot_cost_basis',
        ),
        migrations.RenameField(
            model_name='proformalist',
            old_name='lot_cost',
            new_name='lot_cost_basis',
        ),
        migrations.AddField(
            model_name='proforma',
            name='financing_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proforma',
            name='lot_fmv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proforma',
            name='sales_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proforma',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformalist',
            name='financing_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformalist',
            name='lot_fmv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformalist',
            name='sales_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformalist',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
    ]
