# Generated by Django 3.1.3 on 2020-12-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201207_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformalist',
            name='schedule_days',
            field=models.IntegerField(default=0),
        ),
    ]
