# Generated by Django 3.1.3 on 2020-12-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_proformalist_schedule_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=3)),
                ('permit_notes', models.CharField(choices=[('AT', 'At Truss'), ('AE', 'At Engineering')], default='AT', max_length=100)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.community')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.phase')),
            ],
        ),
    ]
