# Generated by Django 3.1.3 on 2020-12-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformalist',
            name='tied_out',
        ),
    ]
