# Generated by Django 3.1.3 on 2020-12-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201208_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proformalist',
            old_name='update_code',
            new_name='update_description',
        ),
    ]
