# Generated by Django 3.1.3 on 2020-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201208_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformalist',
            name='warranty_cost',
            field=models.IntegerField(default=0),
        ),
    ]
