# Generated by Django 3.1.3 on 2020-12-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_proformalist_warranty_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ('plat__description', 'number')},
        ),
        migrations.RemoveField(
            model_name='job',
            name='community',
        ),
        migrations.AddField(
            model_name='job',
            name='job',
            field=models.CharField(default='000-00-000', max_length=10),
        ),
    ]
