# Generated by Django 3.1.3 on 2020-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20201209_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(default='000-00-000', max_length=10, unique=True),
        ),
    ]
