# Generated by Django 3.1.3 on 2020-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20201209_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.CharField(choices=[('Future', 'Future'), ('Vertical', 'Vertical')], default='Future', max_length=10),
        ),
    ]
