# Generated by Django 3.1.3 on 2020-12-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_phase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='lot_count',
        ),
    ]
