# Generated by Django 3.1.3 on 2020-12-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_plat_lot_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='owner',
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('number', 'plat'), name='unique number'),
        ),
    ]
