# Generated by Django 3.1.3 on 2020-12-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20201209_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='status',
        ),
        migrations.AddField(
            model_name='plat',
            name='status',
            field=models.CharField(choices=[('LD Diligence', 'LD Diligence'), ('LD Future', 'LD Future'), ('LD Construction', 'LD Construction'), ('LD Complete', 'LD Complete'), ('Vertical', 'Vertical')], default='Diligence', max_length=30),
        ),
    ]
