# Generated by Django 3.1.3 on 2020-12-10 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20201209_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phasecontent', to='blog.plat'),
        ),
    ]
