# Generated by Django 3.1.3 on 2020-12-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20201211_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platschedule',
            name='plat',
        ),
        migrations.AddField(
            model_name='plat',
            name='schedule_found',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='GenSchedule',
        ),
        migrations.DeleteModel(
            name='PlatSchedule',
        ),
    ]
