# Generated by Django 3.1.3 on 2020-12-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20201211_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proforma',
            name='proforma_id',
        ),
        migrations.AddField(
            model_name='proforma',
            name='proformalist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.proformalist'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='update_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proforma',
            name='warranty_cost',
            field=models.IntegerField(default=0),
        ),
    ]
