# Generated by Django 3.1.3 on 2020-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20201228_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformalist',
            name='sales_base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proformalist',
            name='update_description',
            field=models.CharField(choices=[('DM', 'Diligence Mtg'), ('PRM', 'Phase Release Mtg'), ('BARM', 'Bi-Annual Review Mtg'), ('BP', 'Base Price')], default='DM', max_length=100),
        ),
    ]
