# Generated by Django 3.1.3 on 2020-12-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20201228_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='sales_base_price',
            field=models.IntegerField(default=0),
        ),
    ]
