# Generated by Django 3.1.3 on 2021-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_proforma_sales_base_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={},
        ),
        migrations.AddField(
            model_name='job',
            name='sales_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proformalist',
            name='update_description',
            field=models.CharField(choices=[('DM', 'Diligence Mtg'), ('PRM', 'Phase Release Mtg'), ('BARM', 'Bi-Annual Review Mtg'), ('BP', 'Sales Base Price')], default='DM', max_length=100),
        ),
    ]
