# Generated by Django 3.1.3 on 2021-01-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210104_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.plans'),
        ),
    ]
