# Generated by Django 3.1.3 on 2021-01-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_job_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='status',
            field=models.CharField(choices=[('LD Diligence', 'LD Diligence'), ('LD Future', 'LD Future'), ('LD Construction', 'LD Construction'), ('LD Complete', 'LD Complete'), ('Vertical', 'Vertical')], default='LD Future', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='proformalist',
            unique_together={('community', 'plan', 'update_description')},
        ),
    ]
