# Generated by Django 3.1.3 on 2021-01-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20210112_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformalist',
            name='sales_base_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
