# Generated by Django 3.1.3 on 2021-01-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_pricing_pricinghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='base_price',
            new_name='price_adjustment',
        ),
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='PricingHistory',
        ),
    ]
