# Generated by Django 3.1.3 on 2021-01-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20210112_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='use_vertical_start_sch',
            field=models.BooleanField(default=False),
        ),
    ]
