# Generated by Django 3.1.3 on 2021-01-18 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_phase_use_vertical_start_sch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='number',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 2 characters', regex='^.{2}$')]),
        ),
        migrations.AlterField(
            model_name='proformalist',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
