# Generated by Django 3.1.3 on 2021-01-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20210118_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('event', models.CharField(choices=[('Sale', 'Sale'), ('Start', 'Start'), ('Closing', 'Closing')], default='Sale', max_length=15)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plat')),
            ],
        ),
    ]
