# Generated by Django 3.1.3 on 2021-01-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='actual_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='actual_sale_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
