# Generated by Django 3.1.3 on 2021-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20210119_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='projected_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='projected_sale_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='projected_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
