# Generated by Django 3.1.3 on 2021-02-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20210121_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.phase'),
        ),
        migrations.AlterField(
            model_name='job',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.plans'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.plat'),
        ),
    ]
