# Generated by Django 3.1.3 on 2021-02-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20210209_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='use_vertical_start_sch',
        ),
        migrations.AddField(
            model_name='plat',
            name='default_start_pace',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
