# Generated by Django 3.1.3 on 2021-02-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_job_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='product_type',
            field=models.CharField(blank=True, choices=[('DFL', 'DFL'), ('DRL', 'DRL'), ('AFL', 'AFL'), ('ARL', 'ARL')], default='DFL', max_length=100, null=True),
        ),
    ]
