# Generated by Django 3.1.3 on 2021-02-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20210211_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proformalist',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.plans'),
        ),
    ]
