# Generated by Django 3.1.3 on 2021-02-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20210212_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='garage_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plans',
            name='stories',
            field=models.IntegerField(default=0),
        ),
    ]
