# Generated by Django 3.1.3 on 2021-02-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20210212_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attached_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='elevation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='garage_orientation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
