# Generated by Django 3.1.3 on 2021-02-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_job_garage_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='projected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
