# Generated by Django 3.1.3 on 2021-02-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_auto_20210215_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sales_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
