# Generated by Django 3.1.3 on 2021-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_job_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
