# Generated by Django 3.1.3 on 2021-02-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_plans_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lot_premium',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
