# Generated by Django 3.1.3 on 2021-02-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_job_lot_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='is_attached',
            field=models.BooleanField(default=0),
        ),
    ]
