# Generated by Django 3.1.3 on 2021-02-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_auto_20210220_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.plat'),
        ),
    ]
