# Generated by Django 3.1.3 on 2021-02-22 20:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_plat_predecessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='est_vert_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='partner name'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='number',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 2 characters', regex='^.{2}$')], verbose_name='phase number'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.plat'),
        ),
    ]
