# Generated by Django 3.1.3 on 2021-02-22 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_auto_20210222_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectedStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plat')),
            ],
        ),
    ]
