# Generated by Django 3.1.6 on 2021-03-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_projectedstart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_id', models.IntegerField(unique=True)),
                ('lender_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
