# Generated by Django 3.1.3 on 2021-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_plat_planned_vert_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='bath_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plans',
            name='bedroom_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plans',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
