# Generated by Django 3.1.3 on 2021-03-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_auto_20210304_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
