# Generated by Django 3.1.3 on 2021-03-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_plans_plan_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='plan_long',
        ),
    ]
