# Generated by Django 3.1.3 on 2021-03-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_remove_plans_plan_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='load',
            field=models.CharField(blank=True, choices=[('Rear', 'Rear'), ('Front', 'Front')], max_length=5, null=True),
        ),
    ]
