# Generated by Django 3.1.3 on 2021-03-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_costcode_loantransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.phase'),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.plans'),
        ),
    ]
