# Generated by Django 3.1.3 on 2021-03-10 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_auto_20210309_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPhaseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BP', 'Base Price'), ('LC', 'Lot Cost'), ('LF', 'Lot FMV'), ('LR', 'Lot Release')], max_length=2)),
                ('amount', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.phase')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plans')),
            ],
        ),
        migrations.RenameField(
            model_name='lender',
            old_name='lender_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='lender_id',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
