# Generated by Django 3.1.3 on 2021-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_auto_20210309_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='description',
            field=models.CharField(editable=False, max_length=30, null=True),
        ),
    ]
