# Generated by Django 3.1.3 on 2021-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_phase_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
