# Generated by Django 3.1.3 on 2021-03-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_auto_20210310_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planphasetransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='planphasetransaction',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='planphasetransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='planphasetransaction',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planphasetransaction',
            name='lot_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planphasetransaction',
            name='lot_fmv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planphasetransaction',
            name='lot_release',
            field=models.IntegerField(default=0),
        ),
    ]
