# Generated by Django 3.1.3 on 2021-03-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0081_auto_20210310_1246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planphasetransaction',
            unique_together={('phase', 'plan')},
        ),
    ]
