# Generated by Django 3.1.3 on 2021-03-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0082_auto_20210310_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(default=0)),
                ('lot_cost', models.IntegerField(default=0)),
                ('lot_fmv', models.IntegerField(default=0)),
                ('lot_release', models.IntegerField(default=0)),
                ('loan_committment', models.IntegerField(default=0)),
                ('receive_cash_back', models.BooleanField(default=0)),
                ('standard', models.CharField(choices=[('Prelude', 'Prelude'), ('Classic', 'Classic'), ('Modern', 'Modern'), ('Signature', 'Signature')], default='Classic', max_length=100)),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.lender')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.phase')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plans')),
            ],
            options={
                'unique_together': {('phase', 'plan')},
            },
        ),
        migrations.DeleteModel(
            name='PlanPhaseTransaction',
        ),
    ]
