# Generated by Django 3.1.3 on 2021-03-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0085_phase_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='loantransaction',
            name='plan',
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='masterplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.masterplan'),
        ),
    ]
