# Generated by Django 3.1.3 on 2021-03-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0086_auto_20210311_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcode',
            name='is_hard',
            field=models.BooleanField(default=1),
        ),
    ]
