# Generated by Django 3.1.3 on 2021-03-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0087_costcode_is_hard'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lender',
            name='ltc_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lender',
            name='ltv_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lender',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
