# Generated by Django 3.1.3 on 2021-03-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0089_auto_20210311_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lender',
            name='ltc_limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lender',
            name='ltv_limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lender',
            name='points',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
