# Generated by Django 3.1.3 on 2021-03-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0090_auto_20210311_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='masterplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.masterplan'),
        ),
    ]
