# Generated by Django 3.1.3 on 2021-03-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0094_auto_20210316_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('traffic_count', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('be_back_count', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lender',
            name='ltv_limit',
        ),
    ]
