# Generated by Django 3.1.3 on 2021-03-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0095_auto_20210316_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='ltv_limit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
