# Generated by Django 3.1.3 on 2021-03-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0095_masterplan_uses_master_appraisal'),
        ('blog', '0096_lender_ltv_limit'),
    ]

    operations = [
    ]
