# Generated by Django 3.1.3 on 2021-03-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0097_merge_20210319_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='community_id',
        ),
        migrations.AddField(
            model_name='traffic',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.community'),
        ),
    ]
