# Generated by Django 3.1.3 on 2021-03-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0098_auto_20210319_1213'),
        ('blog', '0097_merge_20210319_1405'),
    ]

    operations = [
    ]
