# Generated by Django 3.1.3 on 2021-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0099_merge_20210322_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='list_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
