# Generated by Django 3.1.3 on 2021-03-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0100_job_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_long_name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
