# Generated by Django 3.1.7 on 2021-03-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0099_merge_20210322_0947'),
        ('blog', '0101_plans_plan_long_name'),
    ]

    operations = [
    ]
