# Generated by Django 3.1.3 on 2021-03-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0102_merge_20210323_1607'),
        ('blog', '0104_auto_20210323_1503'),
    ]

    operations = [
    ]
