# Generated by Django 3.1.3 on 2021-03-31 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0106_remove_traffic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.plat'),
        ),
    ]
