# Generated by Django 3.1.3 on 2021-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0108_auto_20210331_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='credit_limit',
            field=models.IntegerField(default=0),
        ),
    ]
