# Generated by Django 3.1.3 on 2021-04-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0110_auto_20210412_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='status',
            field=models.CharField(choices=[('LD Diligence', 'LD Diligence'), ('LD Future', 'LD Future'), ('LD Construction', 'LD Construction'), ('LD Complete', 'LD Complete'), ('Recorded', 'Recorded'), ('Vertical', 'Vertical'), ('Closed', 'Closed')], default='LD Future', max_length=30),
        ),
    ]
