# Generated by Django 3.1.7 on 2021-04-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0111_auto_20210412_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='state',
            field=models.CharField(choices=[('WA', 'WA'), ('OR', 'OR')], default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.plat'),
        ),
    ]
