# Generated by Django 3.1.3 on 2021-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0112_auto_20210413_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
