# Generated by Django 3.1.3 on 2021-04-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0113_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='sage_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
