# Generated by Django 3.1.3 on 2021-04-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0114_lender_sage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contingency',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='contingency_exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
