# Generated by Django 3.1.3 on 2021-04-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0115_auto_20210422_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contingency_exp_date',
        ),
        migrations.AlterField(
            model_name='job',
            name='contingency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
