# Generated by Django 3.1.3 on 2021-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0116_auto_20210422_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contingency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
