# Generated by Django 3.1.3 on 2021-04-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0117_auto_20210422_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sales_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
