# Generated by Django 3.1.3 on 2021-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0119_job_base_contract_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
