# Generated by Django 3.1.3 on 2021-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0121_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
