# Generated by Django 3.1.3 on 2021-04-27 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0123_auto_20210427_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_release', models.IntegerField(default=0)),
                ('receive_cash_back', models.BooleanField(default=0)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.lender')),
                ('masterplan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.masterplan')),
            ],
        ),
    ]
