# Generated by Django 3.1.3 on 2021-04-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0124_masterappraisal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterAppraisal',
        ),
    ]
