# Generated by Django 3.1.3 on 2021-04-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0126_masterappraisal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_id', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('required_for_start', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_id', models.IntegerField(unique=True)),
                ('documenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.documenttype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.job')),
            ],
        ),
    ]
