# Generated by Django 3.1.3 on 2021-05-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0127_documenttype_jobattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.IntegerField(default=0),
        ),
    ]
