# Generated by Django 3.1.3 on 2021-05-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0128_auto_20210504_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
