# Generated by Django 3.1.3 on 2021-05-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0129_auto_20210504_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(max_length=50),
        ),
    ]
