# Generated by Django 3.1.3 on 2021-05-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0132_job_original_list_base_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='original_list_base_price',
            new_name='original_base_list_price',
        ),
    ]
