# Generated by Django 3.1.3 on 2021-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0135_buildingpermit'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterappraisal',
            name='plans',
            field=models.ManyToManyField(to='blog.Plans'),
        ),
    ]
