# Generated by Django 3.1.3 on 2021-05-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0136_masterappraisal_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterAppraisal',
            new_name='MasterLoan',
        ),
        migrations.CreateModel(
            name='MasterPlanTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(default=0)),
                ('lot_cost', models.IntegerField(default=0)),
                ('lot_fmv', models.IntegerField(default=0)),
                ('standard', models.CharField(choices=[('Prelude', 'Prelude'), ('Classic', 'Classic'), ('Modern', 'Modern'), ('Signature', 'Signature')], default='Classic', max_length=100)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.phase')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plans')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='plans',
            field=models.ManyToManyField(through='blog.MasterPlanTest', to='blog.Plans'),
        ),
    ]
