# Generated by Django 3.1.3 on 2021-05-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0137_auto_20210527_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterloan',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='masterloan',
            name='plans',
        ),
        migrations.AddField(
            model_name='masterloan',
            name='plans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.masterplantest'),
        ),
    ]
