# Generated by Django 3.1.3 on 2021-05-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0138_auto_20210527_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterloan',
            name='plans',
        ),
        migrations.AddField(
            model_name='masterloan',
            name='masterplans',
            field=models.ManyToManyField(to='blog.MasterPlanTest'),
        ),
    ]
