# Generated by Django 3.1.3 on 2021-06-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0139_auto_20210527_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scheduled_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.phase'),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.plans'),
        ),
    ]
