# Generated by Django 3.1.3 on 2021-06-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0142_auto_20210609_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='permit_notes',
        ),
    ]
