# Generated by Django 3.2 on 2021-06-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0143_remove_job_permit_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField(default=0)),
                ('garage_count', models.IntegerField(default=1)),
                ('stories', models.IntegerField(default=0)),
                ('bedroom_count', models.IntegerField(default=0)),
                ('bath_count', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('width', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=1)),
                ('is_attached', models.BooleanField(default=0)),
                ('full_name', models.CharField(default='none', max_length=50, verbose_name='Plan name')),
                ('load', models.CharField(blank=True, choices=[('Rear', 'Rear'), ('Front', 'Front')], max_length=5, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ('plat__name', 'number')},
        ),
        migrations.AlterModelOptions(
            name='plat',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='community',
            old_name='community_abbreviation',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='community_id',
            new_name='com_id',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='community_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='costcode',
            old_name='cost_code',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_use',
            new_name='use',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='phase',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plat',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='traffic',
            old_name='traffic_count',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='job',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.plan'),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.plan'),
        ),
        migrations.AlterField(
            model_name='masterplantest',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plan'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='plans',
            field=models.ManyToManyField(through='blog.MasterPlanTest', to='blog.Plan'),
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
