# Generated by Django 3.1.3 on 2021-07-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0145_alter_plan_bath_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcode',
            name='description',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='costcode',
            name='number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
