# Generated by Django 3.1.3 on 2021-07-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0145_alter_plan_bath_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('name',), 'verbose_name': 'community', 'verbose_name_plural': 'communities'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='lender',
            options={'ordering': ('name',), 'verbose_name': 'lender', 'verbose_name_plural': 'lenders'},
        ),
        migrations.AlterModelOptions(
            name='masterplan',
            options={'ordering': ('phase', 'plan')},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='traffic',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='job',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
