# Generated by Django 3.1.3 on 2021-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0146_auto_20210702_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterplan',
            name='standard',
            field=models.CharField(blank=True, choices=[('Prelude', 'Prelude'), ('Classic', 'Classic'), ('Modern', 'Modern'), ('Signature', 'Signature')], default=None, max_length=100, null=True),
        ),
    ]
