# Generated by Django 3.1.3 on 2021-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0149_job_fmv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='base_list_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
