# Generated by Django 3.1.3 on 2021-07-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0150_job_base_list_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wms_id', models.IntegerField(unique=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('date_issued', models.DateTimeField()),
                ('issued_by', models.CharField(max_length=50)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('vpo_number', models.CharField(max_length=50)),
            ],
        ),
    ]
