# Generated by Django 3.1.3 on 2021-07-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0151_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vpo_number',
            field=models.IntegerField(),
        ),
    ]
