# Generated by Django 3.2.5 on 2021-07-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0146_auto_20210714_1347'),
        ('blog', '0152_auto_20210719_1200'),
    ]

    operations = [
    ]
