# Generated by Django 3.1.3 on 2021-08-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0152_auto_20210719_1200'),
        ('blog', '0146_auto_20210714_1347'),
    ]

    operations = [
    ]
