# Generated by Django 3.1.3 on 2021-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0153_merge_20210809_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
