# Generated by Django 3.1.3 on 2021-08-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0156_auto_20210810_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterplantest',
            name='description',
            field=models.CharField(default='r', max_length=50),
            preserve_default=False,
        ),
    ]
