# Generated by Django 3.1.3 on 2021-08-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0157_masterplantest_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterplantest',
            options={'ordering': ('description',)},
        ),

    ]
