# Generated by Django 3.1.3 on 2021-08-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0158_auto_20210813_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterloan',
            name='masterplans',
        ),
    ]
