# Generated by Django 3.1.3 on 2021-08-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0160_individualmasterloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterloan',
            name='masterplans',
            field=models.ManyToManyField(through='blog.IndividualMasterLoan', to='blog.MasterPlanTest'),
        ),
    ]
