# Generated by Django 3.1.3 on 2021-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0161_masterloan_masterplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmasterloan',
            name='est_commitment',
            field=models.IntegerField(default=0),
        ),
    ]
