# Generated by Django 3.1.3 on 2021-08-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0162_individualmasterloan_est_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterloan',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
