# Generated by Django 3.1.3 on 2021-08-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0163_masterloan_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='lot_release',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='receive_cash_back',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
