# Generated by Django 3.1.3 on 2021-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0164_auto_20210816_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterplantest',
            name='description',
            field=models.CharField(max_length=75),
        ),
    ]
