# Generated by Django 3.1.3 on 2021-08-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0165_auto_20210816_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
