# Generated by Django 3.1.3 on 2021-08-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0168_auto_20210817_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterloanpackage',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterloanpackage',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterloanpackage',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
