# Generated by Django 3.1.3 on 2021-08-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0169_auto_20210818_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterloan',
            name='appraised_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterloanpackage',
            name='description',
            field=models.CharField(default='h', max_length=50),
            preserve_default=False,
        ),
    ]
