# Generated by Django 3.2.5 on 2021-08-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0172_loan_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterloanpackage',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.community'),
        ),
    ]
