# Generated by Django 3.1.3 on 2021-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0173_masterloanpackage_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterloanpackage',
            options={'ordering': ('description',)},
        ),
        migrations.RemoveField(
            model_name='masterloanpackage',
            name='lot_release',
        ),
        migrations.AddField(
            model_name='masterloan',
            name='lot_release',
            field=models.IntegerField(default=0),
        ),
    ]
