# Generated by Django 3.1.3 on 2021-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0174_auto_20210819_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterPlanTest',
            new_name='PhasePlan',
        ),
        migrations.RenameField(
            model_name='masterloan',
            old_name='masterplantest',
            new_name='PhasePlan',
        ),
        migrations.AddField(
            model_name='masterloanpackage',
            name='standard',
            field=models.CharField(choices=[('Prelude', 'Prelude'), ('Classic', 'Classic'), ('Modern', 'Modern'), ('Signature', 'Signature')], default='Classic', max_length=100),
        ),
    ]
