# Generated by Django 3.1.3 on 2021-08-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0175_auto_20210820_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterloan',
            old_name='PhasePlan',
            new_name='phaseplan',
        ),
        migrations.RenameField(
            model_name='masterloanpackage',
            old_name='masterplans',
            new_name='phaseplans',
        ),
    ]
