# Generated by Django 3.1.3 on 2021-08-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0177_loantransaction_masterloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantransaction',
            old_name='masterloan',
            new_name='phaseplan',
        ),
    ]
