# Generated by Django 3.1.3 on 2021-08-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0179_auto_20210820_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='individual_submission',
            field=models.BooleanField(default=0),
        ),
    ]
