# Generated by Django 3.1.3 on 2021-08-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0180_loan_individual_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterloan',
            name='masterloanpackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.masterloanpackage'),
        ),
    ]
