# Generated by Django 3.1.3 on 2021-08-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0181_auto_20210831_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterloanpackage',
            name='phaseplans',
            field=models.ManyToManyField(null=True, through='blog.MasterLoan', to='blog.PhasePlan'),
        ),
    ]
