# Generated by Django 3.1.3 on 2021-09-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0183_auto_20210831_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='date_posted',
            field=models.DateTimeField(blank=True),
        ),
    ]
