# Generated by Django 3.1.3 on 2021-09-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0185_auto_20210901_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='plans',
            field=models.ManyToManyField(blank=True, through='blog.PhasePlan', to='blog.Plan'),
        ),
    ]
