# Generated by Django 3.1.7 on 2021-09-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0186_auto_20210901_1102'),
        ('blog', '0157_job_past_sheetrock'),
    ]

    operations = [
    ]
