# Generated by Django 3.1.3 on 2021-09-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0187_merge_20210901_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='appraisal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
