# Generated by Django 3.1.3 on 2021-09-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0188_tieout'),
        ('blog', '0188_auto_20210902_1320'),
    ]

    operations = [
    ]
