# Generated by Django 3.1.3 on 2021-09-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0189_merge_20210903_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
