# Generated by Django 3.1.3 on 2021-09-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0189_auto_20210907_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.job'),
        ),
    ]
