# Generated by Django 3.1.3 on 2021-09-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0190_purchaseorder_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.community'),
        ),
    ]
