# Generated by Django 3.1.3 on 2021-09-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0191_auto_20210903_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tieouttask',
            name='commment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
