# Generated by Django 3.1.3 on 2021-09-08 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0192_auto_20210908_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tjob', models.CharField(max_length=10)),
                ('Tphase', models.CharField(blank=True, max_length=9, null=True)),
                ('Trantyp', models.CharField(max_length=25)),
                ('Trandat', models.DateField(blank=True, null=True)),
                ('Tactdat', models.DateField(blank=True, null=True)),
                ('Tamount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Tdracct', models.CharField(max_length=50)),
                ('Tcracct', models.CharField(max_length=50)),
                ('Tcat', models.CharField(max_length=50)),
                ('Extra', models.CharField(max_length=50)),
                ('Commitment', models.CharField(max_length=50)),
                ('Vendor', models.CharField(max_length=50)),
                ('SOURCE', models.CharField(max_length=50)),
                ('date_stamp', models.DateField()),
                ('sage_row_id', models.CharField(max_length=50, unique=True)),
                ('Tinv', models.CharField(max_length=50)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.job')),
            ],
        ),
    ]
