# Generated by Django 3.1.3 on 2021-09-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0194_auto_20210907_0925'),
        ('blog', '0190_purchaseorder_job'),
    ]

    operations = [
    ]
