# Generated by Django 3.1.3 on 2021-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0194_auto_20210908_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Commitment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Extra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='SOURCE',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tactdat',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tcat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tcracct',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tdracct',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tinv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tphase',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Trandat',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Trantyp',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Vendor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
