# Generated by Django 3.1.3 on 2021-09-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0195_merge_20210908_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_issued',
            field=models.DateField(),
        ),
    ]
