# Generated by Django 3.2.7 on 2021-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0196_accountingtransaction_costcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcode',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
