# Generated by Django 3.1.3 on 2021-09-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0196_auto_20210908_1127'),
        ('blog', '0196_accountingtransaction_costcode'),
    ]

    operations = [
    ]
