# Generated by Django 3.2 on 2021-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0197_alter_costcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tphase',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
