# Generated by Django 3.2 on 2021-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0198_alter_accountingtransaction_tphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingtransaction',
            name='is_upgrade',
            field=models.BooleanField(default=0),
        ),
    ]
