# Generated by Django 3.1.3 on 2021-09-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0198_auto_20210909_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieouttask',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
