# Generated by Django 3.2 on 2021-09-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0199_accountingtransaction_is_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterloanpackage',
            name='status',
            field=models.CharField(blank=True, choices=[('gathering_loan_facts', 'Gathering Loan Facts'), ('submitted', 'Submitted'), ('appraised', 'Appraised')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='vertical_launch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
