# Generated by Django 3.2 on 2021-09-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0200_auto_20210928_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='masterplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.masterplan'),
        ),
    ]
