# Generated by Django 3.1.3 on 2021-09-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0201_tieouttask_accountable'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingtransaction',
            name='purchsaeorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tactdat',
            field=models.DateField(null=True, verbose_name='Acctg Date'),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tdracct',
            field=models.CharField(max_length=50, null=True, verbose_name='Debit Account'),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Tphase',
            field=models.CharField(max_length=9, null=True, verbose_name='Cost Code'),
        ),
    ]
