# Generated by Django 3.1.3 on 2021-09-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0202_auto_20210910_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingtransaction',
            old_name='purchsaeorder',
            new_name='purchaseorder',
        ),
    ]
