# Generated by Django 3.2 on 2021-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0202_remove_phase_vertical_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='levels',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='master_on_main',
            field=models.BooleanField(default=0),
        ),
    ]
