# Generated by Django 3.1.3 on 2021-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0203_auto_20210910_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('from_spec', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
