# Generated by Django 3.2 on 2021-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0203_auto_20211006_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
