# Generated by Django 3.1.3 on 2021-09-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0204_salesoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoption',
            name='ss_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
