# Generated by Django 3.1.3 on 2021-09-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0206_auto_20210913_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingoption',
            old_name='description',
            new_name='sage_row_id',
        ),
    ]
