# Generated by Django 3.1.3 on 2021-09-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0207_auto_20210913_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesoption',
            name='accountingoption',
        ),
        migrations.AddField(
            model_name='salesoption',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.job'),
        ),
    ]
