# Generated by Django 3.1.3 on 2021-09-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0208_auto_20210913_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieouttask',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
