# Generated by Django 3.1.3 on 2021-09-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0210_auto_20210915_1504'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='phase',
            index=models.Index(fields=['name'], name='blog_phase_name_7adfda_idx'),
        ),
        migrations.AddIndex(
            model_name='phaseplan',
            index=models.Index(fields=['description'], name='blog_phasep_descrip_c4d1a2_idx'),
        ),
    ]
