# Generated by Django 3.2.7 on 2021-09-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0212_auto_20210922_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieout',
            name='complete',
            field=models.BooleanField(default=0),
        ),
    ]
