# Generated by Django 3.2.7 on 2021-09-22 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0213_tieout_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tieout',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.job'),
        ),
    ]
