# Generated by Django 3.2.7 on 2021-09-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0214_alter_tieout_job'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tieouttask',
            constraint=models.UniqueConstraint(fields=('name', 'tieout'), name='unique name'),
        ),
    ]
