# Generated by Django 3.2 on 2021-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0215_tieouttask_unique name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tieouttask',
            old_name='accountable',
            new_name='last_updated_by',
        ),
        migrations.AddField(
            model_name='tieouttask',
            name='last_update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Job Number'),
        ),
    ]
