# Generated by Django 3.2 on 2021-09-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0218_auto_20210927_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingtransaction',
            name='is_upgrade',
            field=models.BooleanField(default=0),
        ),
    ]
