# Generated by Django 3.2 on 2021-10-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0203_auto_20211006_0919'),
        ('blog', '0220_tieouttask_form_order'),
    ]

    operations = [
    ]
