# Generated by Django 3.2 on 2021-10-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0222_auto_20211006_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcode',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
