# Generated by Django 3.2 on 2021-10-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0223_costcode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieouttask',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='costcode',
            name='costcodecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.costcodecategory', verbose_name='Cost Code Category'),
        ),
        migrations.AlterField(
            model_name='tieouttask',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Task Name'),
        ),
    ]
