# Generated by Django 3.2 on 2021-10-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0224_auto_20211011_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingtransaction',
            name='salesoption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.salesoption'),
        ),
        migrations.AlterField(
            model_name='costcode',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cost Code'),
        ),
    ]
