# Generated by Django 3.2 on 2021-11-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0205_alter_traffic_date'),
        ('blog', '0225_auto_20211014_0905'),
    ]

    operations = [
    ]
