# Generated by Django 3.2 on 2021-11-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0226_merge_0205_alter_traffic_date_0225_auto_20211014_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Commitment',
            field=models.CharField(max_length=50, null=True, verbose_name='PO'),
        ),
        migrations.AlterField(
            model_name='accountingtransaction',
            name='Trandat',
            field=models.DateField(null=True, verbose_name='Tran Date'),
        ),
    ]
