# Generated by Django 3.2 on 2021-11-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0228_auto_20211112_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='lot_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plat',
            name='project_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
