# Generated by Django 3.2 on 2021-11-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0154_scheduledtask_scheduledtaskinstance_task'),
        ('blog', '0229_auto_20211112_1240'),
    ]

    operations = [
    ]
