# Generated by Django 3.2 on 2021-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0229_auto_20211112_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='lot_count',
        ),
        migrations.AddField(
            model_name='plat',
            name='project_lot_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
