# Generated by Django 3.2 on 2021-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0230_merge_20211112_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtaskinstance',
            name='scheduled_task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='community',
            name='procore_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='procore_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ScheduledTask',
        ),
        migrations.DeleteModel(
            name='ScheduledTaskInstance',
        ),
    ]
