# Generated by Django 3.2 on 2021-11-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0231_auto_20211112_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procore_id', models.BigIntegerField(unique=True)),
                ('schedule_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('percent_complete', models.IntegerField(default=0)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('baseline_start', models.DateTimeField(blank=True, null=True)),
                ('baseline_finish', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.BooleanField(default=0)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.plat')),
            ],
        ),
    ]
