# Generated by Django 3.2 on 2021-11-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0232_scheduletask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletask',
            name='schedule_name',
        ),
    ]
