# Generated by Django 3.2 on 2021-11-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0233_remove_scheduletask_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletask',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
