# Generated by Django 3.2 on 2021-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0234_alter_scheduletask_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletask',
            name='baseline_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='baseline_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
