# Generated by Django 3.2 on 2021-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0235_auto_20211117_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plat',
            name='project_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
