# Generated by Django 3.2 on 2021-11-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0236_auto_20211117_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='lot_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
