# Generated by Django 3.2 on 2021-12-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0230_auto_20211119_0828'),
        ('blog', '0237_alter_plat_lot_count'),
    ]

    operations = [
    ]
