# Generated by Django 3.2 on 2021-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0238_merge_20211208_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
