# Generated by Django 3.2 on 2021-12-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0239_alter_plat_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='resource_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
