# Generated by Django 3.2 on 2021-12-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0241_traffic_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='job',
        ),
        migrations.AddField(
            model_name='traffic',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.community'),
        ),
    ]
