# Generated by Django 3.2 on 2021-12-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0242_auto_20211215_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.partner'),
        ),
    ]
