# Generated by Django 3.2 on 2021-12-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0243_community_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('is_complete', models.BooleanField(default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.phase')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaUpdateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(default=0)),
                ('lot_cost', models.IntegerField(default=0)),
                ('lot_fmv', models.IntegerField(default=0)),
                ('phaseplan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.phaseplan')),
                ('proformaupdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.proformaupdate')),
            ],
        ),
    ]
