# Generated by Django 3.2 on 2022-01-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0243_community_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='plat',
        ),
    ]
