# Generated by Django 3.2 on 2021-12-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0244_proformaupdate_proformaupdatedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaupdate',
            name='phaseplans',
            field=models.ManyToManyField(blank=True, through='blog.ProformaUpdateDetail', to='blog.PhasePlan'),
        ),
    ]
