# Generated by Django 3.2 on 2022-01-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0244_remove_traffic_plat'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.plat'),
        ),
    ]
