# Generated by Django 3.2 on 2022-01-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0245_job_plat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.plat'),
        ),
        migrations.CreateModel(
            name='PlatPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=75)),
                ('base_price', models.IntegerField(default=0)),
                ('lot_cost', models.IntegerField(default=0)),
                ('lot_fmv', models.IntegerField(default=0)),
                ('standard', models.CharField(choices=[('Prelude', 'Prelude'), ('Classic', 'Classic'), ('Modern', 'Modern'), ('Signature', 'Signature')], default='Classic', max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plan')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plat')),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.AddIndex(
            model_name='platplan',
            index=models.Index(fields=['description'], name='blog_platpl_descrip_004fc8_idx'),
        ),
    ]
