# Generated by Django 3.2 on 2021-12-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0245_proformaupdate_phaseplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('is_complete', models.BooleanField(default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.phase')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(default=0)),
                ('lot_cost', models.IntegerField(default=0)),
                ('lot_fmv', models.IntegerField(default=0)),
                ('phaseplan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.phaseplan')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.proforma')),
            ],
        ),
        migrations.RemoveField(
            model_name='proformaupdatedetail',
            name='phaseplan',
        ),
        migrations.RemoveField(
            model_name='proformaupdatedetail',
            name='proformaupdate',
        ),
        migrations.DeleteModel(
            name='ProformaUpdate',
        ),
        migrations.DeleteModel(
            name='ProformaUpdateDetail',
        ),
    ]
