# Generated by Django 3.2 on 2021-12-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0246_auto_20211216_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='phaseplans',
            field=models.ManyToManyField(blank=True, through='blog.ProformaDetail', to='blog.PhasePlan'),
        ),
    ]
