# Generated by Django 3.2 on 2022-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0246_auto_20220126_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='plans',
            field=models.ManyToManyField(blank=True, through='blog.PlatPlan', to='blog.Plan'),
        ),
    ]
