# Generated by Django 3.2 on 2022-01-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0248_auto_20220126_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='platplan',
            name='phase_plan_id',
            field=models.IntegerField(default=0),
        ),
    ]
