# Generated by Django 3.2 on 2022-01-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0250_remove_platplan_phaseplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterloan',
            name='platplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.platplan'),
        ),
    ]
