# Generated by Django 3.2 on 2022-01-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0251_masterloan_platplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterloanpackage',
            name='platplans',
            field=models.ManyToManyField(blank=True, through='blog.MasterLoan', to='blog.PlatPlan'),
        ),
    ]
