# Generated by Django 3.2 on 2022-02-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0252_masterloanpackage_platplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.owner'),
        ),
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.phase'),
        ),
        migrations.AlterField(
            model_name='job',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='blog.plat'),
        ),
    ]
