# Generated by Django 3.2 on 2022-01-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0247_proforma_phaseplans'),
        ('blog', '0252_masterloanpackage_platplans'),
    ]

    operations = [
    ]
