# Generated by Django 3.2 on 2022-01-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0253_merge_20220128_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.plat'),
        ),
        migrations.AddField(
            model_name='proformadetail',
            name='platplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.platplan'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='Phase Name'),
        ),
    ]
