# Generated by Django 3.2 on 2022-02-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0253_auto_20220201_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterloan',
            name='phaseplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.phaseplan'),
        ),
    ]
