# Generated by Django 3.2 on 2022-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0254_auto_20220128_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='platplans',
            field=models.ManyToManyField(blank=True, through='blog.ProformaDetail', to='blog.PlatPlan'),
        ),
    ]
