# Generated by Django 3.2 on 2022-01-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0255_proforma_platplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proforma',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='phaseplans',
        ),
        migrations.RemoveField(
            model_name='proformadetail',
            name='phaseplan',
        ),
    ]
