# Generated by Django 3.2 on 2022-01-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0257_auto_20220131_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.community')),
            ],
        ),
        migrations.CreateModel(
            name='ProformaPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.plan')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.proforma')),
            ],
        ),
    ]
