# Generated by Django 3.2 on 2022-01-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0258_proforma_proformaplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('is_complete', models.BooleanField(default=0)),
                ('milestone', models.CharField(choices=[('DueDiligence', 'Due Diligence'), ('Goornogo', 'Go or no go'), ('PlatPlanning', 'Plat Planning')], default='DueDiligence', max_length=50)),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.plat')),
            ],
        ),
        migrations.AddField(
            model_name='proforma',
            name='plans',
            field=models.ManyToManyField(blank=True, through='blog.ProformaPlan', to='blog.Plan'),
        ),
        migrations.CreateModel(
            name='ProformaMilestoneDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(default=0)),
                ('lot_cost', models.IntegerField(default=0)),
                ('lot_fmv', models.IntegerField(default=0)),
                ('proformamilestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.proformamilestone')),
                ('proformaplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.proformaplan')),
            ],
        ),
        migrations.AddField(
            model_name='proformamilestone',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.proforma'),
        ),
    ]
