# Generated by Django 3.2 on 2022-02-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0260_proformamilestone_proformaplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.community')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='proformaplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='proformaplan',
            name='proforma',
        ),
        migrations.RemoveField(
            model_name='proformamilestone',
            name='proforma',
        ),
        migrations.RemoveField(
            model_name='proformamilestone',
            name='proformaplans',
        ),
        migrations.RemoveField(
            model_name='proformamilestonedetail',
            name='proformaplan',
        ),
        migrations.AddField(
            model_name='proformamilestone',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.community'),
        ),
        migrations.AlterField(
            model_name='proformamilestone',
            name='milestone',
            field=models.CharField(choices=[('BusinessPlan', 'Business Plan'), ('Goornogo', 'Go or no go'), ('PlatRelease', 'Plat Release')], default='Goornogo', max_length=50),
        ),
        migrations.DeleteModel(
            name='Proforma',
        ),
        migrations.DeleteModel(
            name='ProformaPlan',
        ),
        migrations.AddField(
            model_name='proformamilestone',
            name='communityplans',
            field=models.ManyToManyField(blank=True, through='blog.ProformaMilestoneDetail', to='blog.CommunityPlan'),
        ),
        migrations.AddField(
            model_name='proformamilestonedetail',
            name='communityplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.communityplan'),
        ),
    ]
