# Generated by Django 3.2 on 2022-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0261_proforma_use_community_not_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='plans',
            field=models.ManyToManyField(blank=True, through='blog.CommunityPlan', to='blog.Plan'),
        ),
    ]
