# Generated by Django 3.2 on 2022-02-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0253_auto_20220201_1036'),
        ('blog', '0262_proforma_add_plans_to_community'),
    ]

    operations = [
    ]
