# Generated by Django 3.2 on 2022-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0263_merge_20220208_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityplan',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proformamilestone',
            name='milestone',
            field=models.CharField(choices=[('BusinessPlan', 'Business Plan'), ('Goornogo', 'Go or no go'), ('PlatRelease', 'Plat Release')], default=None, max_length=50),
        ),
    ]
