# Generated by Django 3.2 on 2022-02-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0265_alter_proformamilestone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityplan',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
