# Generated by Django 3.2 on 2022-02-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0266_alter_communityplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformamilestonedetail',
            name='financing_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformamilestonedetail',
            name='hard_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformamilestonedetail',
            name='permit_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformamilestonedetail',
            name='project_management_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformamilestonedetail',
            name='sales_commission_cost',
            field=models.IntegerField(default=0),
        ),
    ]
