# Generated by Django 3.2 on 2022-02-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0270_importtask_db_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importtask',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterField(
            model_name='proformamilestonedetail',
            name='communityplan',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, to='blog.communityplan'),
            preserve_default=False,
        ),
    ]
