# Generated by Django 3.2 on 2022-02-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0271_auto_20220218_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtaskerror',
            name='row_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='proformamilestone',
            name='communityplans',
            field=models.ManyToManyField(blank=True, through='blog.ProformaMilestoneDetail', to='blog.CommunityPlan', verbose_name='Community Plans'),
        ),
        migrations.AlterField(
            model_name='proformamilestone',
            name='milestone',
            field=models.CharField(choices=[('BusinessPlan', 'BusinessPlan'), ('GoNoGo', 'GoNoGo'), ('PlatRelease', 'PlatRelease')], default=None, max_length=50),
        ),
    ]
