# Generated by Django 3.2 on 2022-02-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0254_alter_masterloan_phaseplan'),
        ('blog', '0272_auto_20220222_1059'),
    ]

    operations = [
    ]
