# Generated by Django 3.2 on 2022-03-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0273_merge_20220224_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='project_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='proformamilestone',
            name='milestone',
            field=models.CharField(choices=[('BusinessPlan', 'BusinessPlan'), ('GoNoGo', 'GoNoGo'), ('VerticalLaunch', 'VerticalLaunch')], default=None, max_length=50),
        ),
    ]
