# Generated by Django 3.2 on 2022-03-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0274_auto_20220308_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='complete',
            field=models.BooleanField(default=0),
        ),
    ]
