# Generated by Django 3.2 on 2022-03-17 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0275_importtask_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformamilestonedetail',
            name='communityplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.communityplan'),
        ),
    ]
