# Generated by Django 3.2 on 2022-03-24 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0276_alter_proformamilestonedetail_communityplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='date_stamp',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.phase'),
        ),
    ]
