# Generated by Django 3.2 on 2022-04-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0279_goal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Reforecast', 'Reforecast')], default='Annual', max_length=15, null=True),
        ),
    ]
