# Generated by Django 3.2 on 2022-04-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0282_loantransaction_purchasingactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='costcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.costcode'),
        ),
    ]
