# Generated by Django 3.2 on 2022-04-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0286_alter_loantransaction_platplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='pahlisch_lot_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
